name: ai
display_name: AI Dev Agent Stack
description: Sada nástrojů pro optimalizaci práce s AI v rámci workspace — účetnictví tokenů, prompt cache, sémantické vyhledávání kódu, model routing.
status: active
type: toolkit
language: python
port:
systemd:
